if(NOT DEFINED OHOS_ARCH OR OHOS_ARCH STREQUAL "")
    message(FATAL_ERROR "OHOS_ARCH must be arm64-v8a or x86_64")
endif()

if(NOT OHOS_ARCH STREQUAL "arm64-v8a" AND NOT OHOS_ARCH STREQUAL "x86_64")
    message(FATAL_ERROR "Unsupported OHOS_ARCH: ${OHOS_ARCH}")
endif()

if(NOT DEFINED OHOS_COMPATIBLE_SDK_VERSION OR OHOS_COMPATIBLE_SDK_VERSION STREQUAL "")
    message(FATAL_ERROR "OHOS_COMPATIBLE_SDK_VERSION must be set")
endif()

set(CLR_CMAKE_TARGET_OS openharmony CACHE STRING "Target operating system" FORCE)
